name: mikebrawanski
favicon: null
layout_spectrum: 0.6144708348438144
typography_spectrum: 0.8270061623770744
title: Mike's World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.1875
  lightness: 0.0625
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
