name: mikebrawanski
favicon: null
layout_spectrum: 0.6144708348438144
typography_spectrum: 0.8270061623770744
title: Mike's World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#352e28'
    - '#5a83b1'
    - '#88a5c3'
    - '#555354'
    - '#cbd8de'
  brandStrength: 0.8125
  lightness: 0.125
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
